galaxy_info:
  role_name: install_jlink
  author: Paul Firs (paulfirs.com)
  description: Install SEGGER J-Link tools for baremetal development.
  license: MIT
  min_ansible_version: 2.9
---
dependencies: []

# Role metadata for install_jlink