---
- name: Get system architecture
  ansible.builtin.setup:
    filter: ansible_architecture

- name: Set J-Link tarball name based on architecture
  set_fact:
    jlink_version: "V7.94a"
    jlink_arch_map:
      x86_64: "JLink_Linux_{{ jlink_version | replace('.', '') }}_x86_64.tgz"
      aarch64: "JLink_Linux_{{ jlink_version | replace('.', '') }}_arm64.tgz"
    jlink_tar: "{{ jlink_arch_map[ansible_facts['ansible_architecture']] }}"
    jlink_url: "https://www.segger.com/downloads/jlink/{{ jlink_arch_map[ansible_facts['ansible_architecture']] }}"
    jlink_dest: "/opt/SEGGER/JLink"

- name: Check if JLinkExe already exists
  stat:
    path: "{{ jlink_dest }}/JLinkExe"
  register: jlinkexe_stat

- name: Ensure destination directory exists
  file:
    path: "{{ jlink_dest }}"
    state: directory
    mode: '0755'
  when: not jlinkexe_stat.stat.exists

- name: Download SEGGER J-Link tarball
  get_url:
    url: "{{ jlink_url }}"
    dest: "/tmp/{{ jlink_tar }}"
    mode: '0644'
  when: not jlinkexe_stat.stat.exists

- name: Extract J-Link to /opt
  unarchive:
    src: "/tmp/{{ jlink_tar }}"
    dest: "{{ jlink_dest }}"
    remote_src: yes
    extra_opts: [--strip-components=1]
  when: not jlinkexe_stat.stat.exists

- name: Ensure JLinkExe is executable
  file:
    path: "{{ jlink_dest }}/JLinkExe"
    mode: '0755'
    state: file
  when: not jlinkexe_stat.stat.exists
