---
- name: Get system architecture
  ansible.builtin.setup:
    filter: ansible_architecture

- name: Set J-Link version
  set_fact:
    jlink_version: "V7.94a"

- name: Set J-Link tarball map
  set_fact:
    jlink_arch_map:
      x86_64: "JLink_Linux_{{ jlink_version | replace('.', '') }}_x86_64.deb"
      aarch64: "JLink_Linux_{{ jlink_version | replace('.', '') }}_arm64.deb"

- name: Set J-Link tarball variables
  set_fact:
    jlink_deb: "{{ jlink_arch_map[ansible_facts.architecture] }}"
    jlink_url: "https://www.segger.com/downloads/jlink/{{ jlink_arch_map[ansible_facts.architecture] }}"
    jlink_dest: "/opt/SEGGER/JLink"

- name: Check if JLinkExe already exists
  stat:
    path: "{{ jlink_dest }}/JLinkExe"
  register: jlinkexe_stat

- name: Ensure destination directory exists
  become: true
  file:
    path: "{{ jlink_dest }}"
    state: directory
    mode: '0755'
  when: not jlinkexe_stat.stat.exists

- name: Download SEGGER J-Link .deb
  shell: |
    wget --post-data "accept_license_agreement=accepted" \
      {{ jlink_url }} \
      -O /tmp/{{ jlink_deb }}
  when: not jlinkexe_stat.stat.exists

- name: Install SEGGER J-Link .deb
  become: true
  shell: dpkg --force-depends -i /tmp/{{ jlink_deb }}
  when: not jlinkexe_stat.stat.exists

- name: Remove J-Link .deb
  file:
    path: "/tmp/{{ jlink_deb }}"
    state: absent
  when: not jlinkexe_stat.stat.exists

- name: Ensure JLinkExe is executable
  file:
    path: "{{ jlink_dest }}/JLinkExe"
    mode: '0755'
    state: file
  when: not jlinkexe_stat.stat.exists
